In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('data/final_cossim_result.csv')
df.head()

,성구분,카테고리명,상품명,CategoryID,ProductID,pink_cossim,blue_cossim,파일명
0,girl,girl-Doll,[d]아망스 커플바니인형 핑크-소형(50cm),C10100020002,L000000549595,0.30838029172372905,-0.26945756131260523,C10100020002-L000000549595.png
1,boy,boy-Car/Train,미판매상품 안내페이지,C10100030004,8809311140519,0.3774832204826477,-0.23083346459605103,C10100030004-8809311140519.png
2,boy,boy-Car/Train,사파리 월드카,C10100030004,8809285520850,-0.34374026732040036,-0.618007212750039,C10100030004-8809285520850.png
3,girl,girl-Deco,헬로키티 요정의드레스룸,C10100020003,L000000578099,0.26004839180984674,-0.2991907872312086,C10100020003-L000000578099.png
4,girl,girl-RolePlay,미판매상품 안내페이지,C10100020001,3032163105008,-0.5579422839012692,0.3219268165432647,C10100020001-3032163105008.png

In [3]:
df.shape

(4340, 8)

In [4]:
df = df[df['pink_cossim'] != 'Error']

In [5]:
df = df[df['pink_cossim'] != 'Error2']

In [6]:
df[df['blue_cossim'] == 'Error2']

,성구분,카테고리명,상품명,CategoryID,ProductID,pink_cossim,blue_cossim,파일명
3120,girl,girl-RolePlay,미판매상품 안내페이지,C10100020001,L000002673397,0.5135129795408317,Error2,C10100020001-L000002673397.png

In [8]:
df = df[df['blue_cossim'] != 'Error2']

In [11]:
df[df['blue_cossim'] == 'Error']

,성구분,카테고리명,상품명,CategoryID,ProductID,pink_cossim,blue_cossim,파일명
3209,girl,girl-Doll,펫샵 아기 허스키,C10100020002,8804275680064,0.115261251237934,Error,C10100020002-8804275680064.png
3251,girl,girl-Doll,브리오 인형 카트-31370,C10100020002,L000002819326,0.6576305047138171,Error,C10100020002-L000002819326.png
3433,girl,girl-Doll,딸기 봉제인형-줄줄이(30cm)/딸기인형/캐릭터인형/인형선물,C10100020002,L000002822525,0.5006818838393702,Error,C10100020002-L000002822525.png
3611,boy,boy-Car/Train,미판매상품 안내페이지,C10100030004,L000002802775,0.07970304380410319,Error,C10100030004-L000002802775.png
3717,boy,boy-Action,미판매상품 안내페이지,C10100030002,8809282303845,-0.3982999675657195,Error,C10100030002-8809282303845.png
3744,girl,girl-Doll,AA 브라운 빅 베어,C10100020002,0803516652653,0.41270919033629333,Error,C10100020002-0803516652653.png
3819,girl,girl-Doll,실바니안패밀리 실바니안 클래식소녀방세트(5162),C10100020002,8711915017015,0.41929757436585635,Error,C10100020002-8711915017015.png
4188,girl,girl-Deco,코코밍 루루밍,C10100020003,8809556745531,0.33594740245584337,Error,C10100020003-8809556745531.png

In [12]:
df = df[df['blue_cossim'] != 'Error']

In [13]:
df[['pink_cossim', 'blue_cossim']] = df[['pink_cossim', 'blue_cossim']].astype('float64')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4296 entries, 0 to 4339
Data columns (total 8 columns):
성구분            4296 non-null object
카테고리명          4296 non-null object
상품명            4296 non-null object
CategoryID     4296 non-null object
ProductID      4296 non-null object
pink_cossim    4296 non-null float64
blue_cossim    4295 non-null float64
파일명            4296 non-null object
dtypes: float64(2), object(6)
memory usage: 302.1+ KB

In [15]:
df_gender = df.groupby(df.성구분).mean()
df_gender

      pink_cossim  blue_cossim
성구분
boy      0.175681    -0.158715
girl     0.320902    -0.253900

In [16]:
df.groupby(df.성구분).std()

      pink_cossim  blue_cossim
성구분
boy      0.273421     0.355427
girl     0.298058     0.370905

In [17]:
df_cate = df.groupby(df.카테고리명).mean()
df_cate

               pink_cossim  blue_cossim
카테고리명
boy-Action        0.183856    -0.213254
boy-Car/Train     0.177080    -0.134885
boy-Control       0.219241    -0.175712
boy-Figure        0.175068    -0.120527
boy-RolePlay      0.117703    -0.147276
girl-DIY          0.246360    -0.171764
girl-Deco         0.415203    -0.174937
girl-Doll         0.316068    -0.292184
girl-RolePlay     0.333109    -0.244986

In [18]:
df.groupby(df.카테고리명).std()

               pink_cossim  blue_cossim
카테고리명
boy-Action        0.269962     0.359322
boy-Car/Train     0.283018     0.332697
boy-Control       0.292447     0.360845
boy-Figure        0.268918     0.370072
boy-RolePlay      0.241683     0.354344
girl-DIY          0.283003     0.311046
girl-Deco         0.315013     0.348477
girl-Doll         0.299434     0.394371
girl-RolePlay     0.266950     0.313097

In [19]:
df.head()

,성구분,카테고리명,상품명,CategoryID,ProductID,pink_cossim,blue_cossim,파일명
0,girl,girl-Doll,[d]아망스 커플바니인형 핑크-소형(50cm),C10100020002,L000000549595,0.308380,-0.269458,C10100020002-L000000549595.png
1,boy,boy-Car/Train,미판매상품 안내페이지,C10100030004,8809311140519,0.377483,-0.230833,C10100030004-8809311140519.png
2,boy,boy-Car/Train,사파리 월드카,C10100030004,8809285520850,-0.343740,-0.618007,C10100030004-8809285520850.png
3,girl,girl-Deco,헬로키티 요정의드레스룸,C10100020003,L000000578099,0.260048,-0.299191,C10100020003-L000000578099.png
4,girl,girl-RolePlay,미판매상품 안내페이지,C10100020001,3032163105008,-0.557942,0.321927,C10100020001-3032163105008.png

In [21]:
df.describe()

       pink_cossim  blue_cossim
count  4296.000000  4295.000000
mean      0.257790    -0.212524
std       0.296452     0.367260
min      -0.987428    -0.966253
25%       0.071118    -0.478827
50%       0.277675    -0.226047
75%       0.462642     0.034014
max       0.985633     0.891407

In [40]:
df['pink_bin'] = pd.qcut(df['pink_cossim'], 4, labels=['never pinky','not pinky','pinky','the most pinky'])
df.head()

,성구분,카테고리명,상품명,CategoryID,ProductID,pink_cossim,blue_cossim,파일명,pink_bin
0,girl,girl-Doll,[d]아망스 커플바니인형 핑크-소형(50cm),C10100020002,L000000549595,0.308380,-0.269458,C10100020002-L000000549595.png,pinky
1,boy,boy-Car/Train,미판매상품 안내페이지,C10100030004,8809311140519,0.377483,-0.230833,C10100030004-8809311140519.png,pinky
2,boy,boy-Car/Train,사파리 월드카,C10100030004,8809285520850,-0.343740,-0.618007,C10100030004-8809285520850.png,never pinky
3,girl,girl-Deco,헬로키티 요정의드레스룸,C10100020003,L000000578099,0.260048,-0.299191,C10100020003-L000000578099.png,not pinky
4,girl,girl-RolePlay,미판매상품 안내페이지,C10100020001,3032163105008,-0.557942,0.321927,C10100020001-3032163105008.png,never pinky

In [41]:
df['blue_bin'] = pd.qcut(df['blue_cossim'], 4, labels=['never blue', 'not blue', 'bluish', 'the most bluish'])
df.head()

,성구분,카테고리명,상품명,CategoryID,ProductID,pink_cossim,blue_cossim,파일명,pink_bin,blue_bin
0,girl,girl-Doll,[d]아망스 커플바니인형 핑크-소형(50cm),C10100020002,L000000549595,0.308380,-0.269458,C10100020002-L000000549595.png,pinky,not blue
1,boy,boy-Car/Train,미판매상품 안내페이지,C10100030004,8809311140519,0.377483,-0.230833,C10100030004-8809311140519.png,pinky,not blue
2,boy,boy-Car/Train,사파리 월드카,C10100030004,8809285520850,-0.343740,-0.618007,C10100030004-8809285520850.png,never pinky,never blue
3,girl,girl-Deco,헬로키티 요정의드레스룸,C10100020003,L000000578099,0.260048,-0.299191,C10100020003-L000000578099.png,not pinky,not blue
4,girl,girl-RolePlay,미판매상품 안내페이지,C10100020001,3032163105008,-0.557942,0.321927,C10100020001-3032163105008.png,never pinky,the most bluish

In [42]:
df.to_csv('data/final_cossim_result.csv', index=False)

# 이제 프로젝트 정리만 남았네요!

프로젝트 목적, 목표 등 설명 - 문제점에 대하여

어떤 방식인지 설명

우리의 방식이 타당하다는 증명 - 높은 점수를 받은 것들을 사진과 함께 확인

결과 공유 - 여자 남자로 나누어 pink & blue cossim 점수가 어떤지 확인, 그래프 등